name: publiccode.yml validation

#on: [pull_request, push]
on:
  workflow_dispatch:

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: italia/publiccode-parser-action@v1
        with:
          publiccode: 'publiccode.yml'
